/**
 * Turns the synthesized stack template into the AWS Infrastructure Composer drawing committed at
 * server/infra/composer/template.json (regenerated by the pre-commit hook). The drawing is never
 * deployed — deploys use cdk.out.
 *
 * Every resource of the real stack is kept, with its real type and properties. The drawing only:
 *   1. renames hashed logical IDs after their constructs, without the top-level construct
 *      (Compute/Function/ServiceRole → FunctionServiceRole, an API route → PublicRoute)
 *   2. drops what differs between machines, so every OS generates the same file: CDK path
 *      metadata, the bootstrap-version parameter and rule, asset hashes, CRLF line endings
 *   3. works around what Composer cannot draw:
 *      - its CloudFront card only draws the first S3 origin and its functions, so the API,
 *        certificate and origin access control get a reference back to the distribution (a tag
 *        or description) and are drawn connected to it. The assets bucket (second S3 origin)
 *        cannot be: Composer's S3 card draws nothing from its own references.
 *      - its S3 card rejects bucket names with dots, so they are spelled as Fn::Join
 *   4. boxes the cards into groups (AWS::Composer::Groups): Edge, Api, Compute, Storage, Auth
 *
 * Checked by rendering the output in the Composer build the AWS Toolkit loads.
 */

type Json = null | boolean | number | string | Json[] | JsonObject;
interface JsonObject {
  [key: string]: Json;
}

interface CfnResource {
  Type: string;
  Properties?: JsonObject;
  DependsOn?: string | string[];
  Metadata?: JsonObject;
  [key: string]: Json | undefined;
}

export interface CfnTemplate {
  Description?: string;
  Parameters?: JsonObject;
  Rules?: JsonObject;
  Resources: Record<string, CfnResource>;
  Outputs?: JsonObject;
  Metadata?: JsonObject;
  [key: string]: unknown;
}

export const COMPOSER_GROUPS = ['Edge', 'Api', 'Compute', 'Storage', 'Auth'] as const;
export type ComposerGroup = (typeof COMPOSER_GROUPS)[number];

/** Top-level construct (second CDK path segment) → group box. */
const GROUP_OF_CONSTRUCT: Record<string, ComposerGroup> = {
  Edge: 'Edge',
  Email: 'Edge',
  Api: 'Api',
  Compute: 'Compute',
  Storage: 'Storage',
  Auth: 'Auth',
};

const CDK_INTERNAL_TYPES = new Set(['AWS::CDK::Metadata']);
const BOOTSTRAP_PARAMETER = 'BootstrapVersion';
const BOOTSTRAP_RULE = 'CheckBootstrapVersion';
const LINK_TAG = 'composer:used-by';

const isObject = (value: Json | undefined): value is JsonObject =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

function mapJson(value: Json, visit: (node: JsonObject) => Json | undefined): Json {
  if (Array.isArray(value)) return value.map((v) => mapJson(v, visit));
  if (!isObject(value)) return value;
  const replaced = visit(value);
  if (replaced !== undefined) return replaced;
  return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, mapJson(v, visit)]));
}

const SUB_VARIABLE = /\$\{([A-Za-z0-9]+)(\.[^}]*)?\}/g;

/** Logical IDs a value points at through Ref, Fn::GetAtt or Fn::Sub. */
function referencedIds(value: Json): Set<string> {
  const ids = new Set<string>();
  mapJson(value, (node) => {
    if (typeof node['Ref'] === 'string') ids.add(node['Ref']);
    const getAtt = node['Fn::GetAtt'];
    if (Array.isArray(getAtt) && typeof getAtt[0] === 'string') ids.add(getAtt[0]);
    const sub = node['Fn::Sub'];
    const text = typeof sub === 'string' ? sub : Array.isArray(sub) ? sub[0] : undefined;
    if (typeof text === 'string') for (const m of text.matchAll(SUB_VARIABLE)) ids.add(m[1] ?? '');
    return undefined;
  });
  return ids;
}

function cdkPath(resource: CfnResource): string[] {
  const path = resource.Metadata?.['aws:cdk:path'];
  return typeof path === 'string' ? path.split('/') : [];
}

/** ANY--api--public--{proxy+} → PublicRoute */
function routeName(segment: string): string | undefined {
  const match = /^[A-Z]+--(.+)$/.exec(segment);
  if (match?.[1] === undefined) return undefined;
  const words = match[1]
    .split('--')
    .filter((w) => w !== 'api' && !w.startsWith('{'))
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1));
  return `${words.join('')}Route`;
}

/**
 * Name from the construct path below the top-level construct: the last two meaningful segments
 * (UserPool/Client → UserPoolClient), or a route's own name.
 */
function readableNames(resource: CfnResource): string[] {
  const segments = cdkPath(resource)
    .slice(2)
    .filter((s) => s !== 'Resource' && s !== 'Default')
    .map((s) => routeName(s) ?? s.replace(/[^A-Za-z0-9]/g, ''));
  const last = segments[segments.length - 1];
  if (last === undefined) return [];
  const short = last.endsWith('Route') ? last : segments.slice(-2).join('');
  return [short, segments.join('')];
}

const ASSET_KEY = /^[0-9a-f]{64}(\.[a-z]+)?$/;

/** Same output on every OS: LF line endings, no content hashes. */
function normalize(value: Json): Json {
  if (typeof value === 'string') {
    const text = value.replace(/\r\n/g, '\n');
    return ASSET_KEY.test(text) ? text.replace(/^[0-9a-f]{64}/, 'asset') : text;
  }
  if (Array.isArray(value)) return value.map(normalize);
  if (isObject(value))
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, normalize(v)]));
  return value;
}

/**
 * Composer folds some resources into another resource's card, and a group may only list the
 * resource that card is keyed by (anything else makes Composer reject the file as incompatible).
 * These are the Composer grouping rules this stack hits:
 *   ApiGatewayV2 route/integration/stage/authorizer → the Api they reference
 *   Lambda::Permission                               → the non-function resource it references
 *   IAM::Policy                                      → the Role it references
 *   S3::BucketPolicy                                 → the Bucket it references
 *   Custom:: resources                               → the Lambda function behind them
 *   anything that references a Logs::LogGroup        → that log group (the function's card)
 */
export function cardRoot(template: CfnTemplate, id: string, depth = 0): string {
  const resource = template.Resources[id];
  if (resource === undefined || depth > 5) return id;
  const refs = [...referencedIds(resource.Properties ?? {})].filter(
    (ref) => template.Resources[ref] !== undefined,
  );
  const typeOf = (ref: string): string => template.Resources[ref]?.Type ?? '';
  const into = (predicate: (type: string) => boolean): string | undefined => {
    const target = refs.find((ref) => predicate(typeOf(ref)));
    return target === undefined ? undefined : cardRoot(template, target, depth + 1);
  };

  const { Type: type } = resource;
  const folded =
    type.startsWith('AWS::ApiGatewayV2::') && type !== 'AWS::ApiGatewayV2::Api'
      ? into((t) => t === 'AWS::ApiGatewayV2::Api')
      : type === 'AWS::Lambda::Permission'
        ? into((t) => t !== 'AWS::Lambda::Function')
        : type === 'AWS::IAM::Policy'
          ? into((t) => t === 'AWS::IAM::Role')
          : type === 'AWS::S3::BucketPolicy'
            ? into((t) => t === 'AWS::S3::Bucket')
            : type.startsWith('Custom::')
              ? into((t) => t === 'AWS::Lambda::Function')
              : refs.find((ref) => typeOf(ref) === 'AWS::Logs::LogGroup');
  return folded ?? id;
}

/**
 * Composer's S3 card rejects bucket names containing dots (ours are the stage domain) and then
 * drops every connection to the bucket. The same name spelled as Fn::Join is not validated.
 */
function spellBucketNamesForComposer(resources: Record<string, CfnResource>): void {
  for (const r of Object.values(resources)) {
    const name = r.Properties?.['BucketName'];
    if (r.Type === 'AWS::S3::Bucket' && typeof name === 'string' && name.includes('.')) {
      (r.Properties ??= {})['BucketName'] = { 'Fn::Join': ['', [name]] };
    }
  }
}

/** Types whose Composer card draws nothing from its own references, so a link would not show. */
const UNLINKABLE_TYPES = new Set(['AWS::S3::Bucket']);

/** Adds a reference to `targetId` on a resource Composer would otherwise draw unconnected. */
function addLink(resource: CfnResource, targetId: string): void {
  if (UNLINKABLE_TYPES.has(resource.Type)) return;
  const props = (resource.Properties ??= {});
  const ref = { Ref: targetId };
  switch (resource.Type) {
    case 'AWS::ApiGatewayV2::Api': {
      const tags = isObject(props['Tags']) ? props['Tags'] : {};
      props['Tags'] = { ...tags, [LINK_TAG]: ref };
      return;
    }
    case 'AWS::CloudFront::OriginAccessControl': {
      const config = isObject(props['OriginAccessControlConfig'])
        ? props['OriginAccessControlConfig']
        : {};
      props['OriginAccessControlConfig'] = {
        ...config,
        Description: { 'Fn::Sub': `Used by \${${targetId}}` },
      };
      return;
    }
    default: {
      const tags = Array.isArray(props['Tags']) ? props['Tags'] : [];
      props['Tags'] = [...tags, { Key: LINK_TAG, Value: ref }];
    }
  }
}

/**
 * What Composer's CloudFront card draws by itself: the bucket behind the first origin's domain
 * name and the functions in function associations.
 */
function drawnByDistribution(distribution: CfnResource): Set<string> {
  const config = distribution.Properties?.['DistributionConfig'];
  if (!isObject(config)) return new Set();
  const origins = Array.isArray(config['Origins']) ? config['Origins'] : [];
  const firstOrigin = origins[0];
  const behaviors = [
    config['DefaultCacheBehavior'] ?? null,
    ...(Array.isArray(config['CacheBehaviors']) ? config['CacheBehaviors'] : []),
  ];
  const functionArns = behaviors.flatMap((b) =>
    isObject(b) && Array.isArray(b['FunctionAssociations'])
      ? b['FunctionAssociations'].map((a) => (isObject(a) ? (a['FunctionARN'] ?? null) : null))
      : [],
  );
  return referencedIds([
    isObject(firstOrigin) ? (firstOrigin['DomainName'] ?? null) : null,
    ...functionArns,
  ]);
}

export function toComposerTemplate(source: CfnTemplate): CfnTemplate {
  const kept = Object.entries(source.Resources).filter(([, r]) => !CDK_INTERNAL_TYPES.has(r.Type));

  // 1. Readable, unique names.
  const rename = new Map<string, string>();
  const used = new Set<string>();
  for (const [id, r] of kept) {
    const candidates = readableNames(r);
    let name = candidates.find((c) => c !== '' && !used.has(c)) ?? candidates[0] ?? id;
    for (let n = 2; used.has(name); n++) name = `${candidates[0] ?? id}${String(n)}`;
    used.add(name);
    rename.set(id, name);
  }

  const renameRefs = (value: Json): Json =>
    mapJson(value, (node): Json | undefined => {
      if (typeof node['Ref'] === 'string') {
        return { Ref: rename.get(node['Ref']) ?? node['Ref'] };
      }
      const getAtt = node['Fn::GetAtt'];
      if (Array.isArray(getAtt) && typeof getAtt[0] === 'string') {
        return { 'Fn::GetAtt': [rename.get(getAtt[0]) ?? getAtt[0], ...getAtt.slice(1)] };
      }
      const sub = node['Fn::Sub'];
      const swap = (text: string): string =>
        text.replace(SUB_VARIABLE, (m, id: string, rest: string | undefined) =>
          rename.has(id) ? `\${${rename.get(id) ?? id}${rest ?? ''}}` : m,
        );
      if (typeof sub === 'string') return { 'Fn::Sub': swap(sub) };
      if (Array.isArray(sub) && typeof sub[0] === 'string') {
        return { 'Fn::Sub': [swap(sub[0]), ...sub.slice(1).map(renameRefs)] };
      }
      return undefined;
    });

  // 2. Resources with their real types and properties, minus CDK/machine-specific noise.
  const resources: Record<string, CfnResource> = {};
  for (const [id, r] of kept) {
    const rest: Record<string, Json | undefined> = { ...r };
    delete rest['Metadata'];
    const resource = normalize(renameRefs(rest as JsonObject)) as CfnResource;
    if (resource.DependsOn !== undefined) {
      resource.DependsOn = ([] as string[])
        .concat(resource.DependsOn)
        .map((d) => rename.get(d) ?? d);
    }
    resources[rename.get(id) ?? id] = resource;
  }

  const drawing: CfnTemplate = {
    AWSTemplateFormatVersion: '2010-09-09',
    ...(source.Description === undefined ? {} : { Description: source.Description }),
    Metadata: {},
    Parameters: Object.fromEntries(
      Object.entries(source.Parameters ?? {}).filter(([k]) => k !== BOOTSTRAP_PARAMETER),
    ),
    ...(source['Mappings'] === undefined ? {} : { Mappings: source['Mappings'] }),
    Resources: resources,
    ...(source.Outputs === undefined ? {} : { Outputs: renameRefs(source.Outputs) as JsonObject }),
  };
  const rules = Object.entries(source.Rules ?? {}).filter(([k]) => k !== BOOTSTRAP_RULE);
  if (rules.length > 0) drawing.Rules = Object.fromEntries(rules);

  // 3. Work around what Composer cannot draw: dotted bucket names, the distribution's other origins.
  spellBucketNamesForComposer(resources);
  for (const [name, r] of Object.entries(resources)) {
    if (r.Type !== 'AWS::CloudFront::Distribution') continue;
    const drawn = drawnByDistribution(r);
    for (const target of referencedIds(r.Properties ?? {})) {
      const linked = resources[target];
      if (linked !== undefined && !drawn.has(target)) addLink(linked, name);
    }
  }

  // 4. Group boxes, listing each card once by the resource Composer keys it by.
  const groups = new Map<ComposerGroup, string[]>(COMPOSER_GROUPS.map((g) => [g, []]));
  for (const [id, r] of kept) {
    const group = GROUP_OF_CONSTRUCT[cdkPath(r)[1] ?? ''];
    const members = group === undefined ? undefined : groups.get(group);
    const root = cardRoot(drawing, rename.get(id) ?? id);
    if (members !== undefined && !members.includes(root)) members.push(root);
  }
  drawing.Metadata = {
    'AWS::Composer::Groups': Object.fromEntries(
      [...groups]
        .filter(([, members]) => members.length > 0)
        .map(([label, members]) => [label, { Label: label, Members: members }]),
    ),
  };

  return drawing;
}

/**
 * The file content, formatted exactly as Composer saves JSON templates (tab indentation, no
 * trailing newline). Composer rewrites the file when it is opened, so any other format would
 * leave the committed drawing modified after every look.
 */
export function serializeComposerTemplate(drawing: CfnTemplate): string {
  return JSON.stringify(drawing, null, '\t');
}

/** Every Ref / GetAtt / Sub / DependsOn in the drawing points at a resource or parameter that exists. */
export function danglingReferences(template: CfnTemplate): string[] {
  const known = new Set([
    ...Object.keys(template.Resources),
    ...Object.keys(template.Parameters ?? {}),
  ]);
  const missing = new Set<string>();
  const check = (id: string): void => {
    if (!known.has(id) && !id.startsWith('AWS::')) missing.add(id);
  };
  for (const r of Object.values(template.Resources)) {
    for (const id of referencedIds(r as unknown as Json)) check(id);
    for (const d of ([] as string[]).concat(r.DependsOn ?? [])) check(d);
  }
  for (const id of referencedIds(template.Outputs ?? {})) check(id);
  return [...missing];
}
