#!/bin/sh
set -e

npx lint-staged --quiet

if git diff --cached --name-only | grep -q "^client/"; then
  (
    cd client
    npm run build
    npx eslint . --max-warnings 0
  )
fi

if git diff --cached --name-only | grep -q "^server/"; then
  (
    cd server
    npm run build
    npx eslint . --max-warnings 0
  )
fi
